{
  imports = [
    ./gc.nix
    ./nmhn.nix
    ./env.nix
    ./user.nix
    ./zram.nix
    ./fonts.nix
    ./locale.nix
    ./sound.nix
    #./opengl.nix
    ./xserver.nix
    ./services.nix
    #./hyprland.nix
    ./packages.nix
    #./bootloader.nix
    ./nixvim/nixvim.nix
  ];
}
